
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class UserView extends javax.swing.JFrame implements Observer{

    private User user;
    private List<User> users;
    private List<String> IDs;
    private DefaultListModel<String> following;
    private DefaultListModel<String> newsFeed;
    
    public UserView( User user, List<User> users, List<String> id ) {
        this.user = user;
        this.users = users;
        IDs = id;
        following = new DefaultListModel<String>();
        newsFeed = new DefaultListModel<String>();
        if(user.getNews().size() != 0){ //update newsfeed from following
             for(String msgs: user.getNews())
                newsFeed.addElement(msgs);
                NewsFeed.setModel(newsFeed);
             }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserIDArea = new javax.swing.JTextField();
        FollowUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        CurrentFollowing = new javax.swing.JList<>();
        TweetMessage = new javax.swing.JTextField();
        Tweet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        NewsFeed = new javax.swing.JList<>();
        Label = new javax.swing.JLabel();
        creation = new javax.swing.JLabel();
        update = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserIDArea.setText("User ID");
        UserIDArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserIDAreaActionPerformed(evt);
            }
        });

        FollowUser.setText("Follow");
        FollowUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FollowUserActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(CurrentFollowing);

        TweetMessage.setText("Tweet Message");

        Tweet.setText("Tweet");
        Tweet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TweetActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(NewsFeed);

        Label.setText(user.getID() + " User View"
        );

        creation.setText("Created at: " + user.getCreationTime());

        update.setText( "Last Updated at: " + user.getLastUpDateTime());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creation)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Label)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TweetMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Tweet))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(UserIDArea, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FollowUser))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(update)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(creation)
                .addGap(28, 28, 28)
                .addComponent(update)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UserIDArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FollowUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TweetMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tweet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //not needed, cannot delete
    private void UserIDAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserIDAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserIDAreaActionPerformed

    
    private void FollowUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FollowUserActionPerformed
        if (!IDs.contains(UserIDArea.getText())) {//check if user exists
            JOptionPane.showMessageDialog(null, "User does not exist.", "Follow Error", JOptionPane.INFORMATION_MESSAGE);
            UserIDArea.setText("");
            return;
        } else if (user.getFollowers().contains(UserIDArea.getText())) {//check if already following
            JOptionPane.showMessageDialog(null, "You are already following this user.", "Follow Error", JOptionPane.INFORMATION_MESSAGE);
        } else {
            following.addElement(UserIDArea.getText()); //add to JList
            CurrentFollowing.setModel(following);
            int index = 0;
            for(User use : users) //get index of person to follow
                if(use.getID().equals(UserIDArea))
                    index = users.indexOf(use);
            user.attach(users.get(index)); //attach to their following list
            
        }
        
        UserIDArea.setText("");
    }//GEN-LAST:event_FollowUserActionPerformed

    private void TweetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TweetActionPerformed
         if (TweetMessage.getText().equals("")) {//empty input error
            JOptionPane.showMessageDialog(null, "Nothing Tweeted", "No Tweet", JOptionPane.INFORMATION_MESSAGE);
        } else{
             user.message(TweetMessage.getText());
             user.setLastUpdateTime();
             newsFeed.addElement("Me: " + TweetMessage.getText()); //add to own newsfeed
             NewsFeed.setModel(newsFeed);
             TweetMessage.setText("");
         }
         List<User> notify = user.getFollowers();//notify followers of tweet
         String message = user.getID() + " - " + TweetMessage.getText();
         for(User observer: notify){
           observer.addNews(message);
         }
    }//GEN-LAST:event_TweetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> CurrentFollowing;
    private javax.swing.JButton FollowUser;
    private javax.swing.JLabel Label;
    private javax.swing.JList<String> NewsFeed;
    private javax.swing.JButton Tweet;
    private javax.swing.JTextField TweetMessage;
    private javax.swing.JTextField UserIDArea;
    private javax.swing.JLabel creation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel update;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
